### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ruinedpeach** [dipjyoti92/StarGAN-Voice-Conversion-2#1]
When I run **preprocess.py**, it remind me of the error "TypeError: expected str, bytes or os.PathLike object, not NoneType" in line 28 "subprocess.call(["sox", wav_from,"-r", "16000", wav_to, "gain", "-h" ,"dither","-s"])".
However, I didn't know how to fix it.

Thanks in advance.

**Comment by dipjyoti92** [comment]
@ruinedpeach 
Please check wav_from/wav_to. It should be the strings of wave file paths from where/to where we are importing/saving the wave files for preprocessing.
Also, make sure you have sox installed in your machine.
