### ISSUE TITLE
How much MCD did u reach? 

### ISSUE THREAD

**Issue by Lukelluke** [dipjyoti92/StarGAN-Voice-Conversion-2#2]
Hi, @dipjyoti92 

We noticed stargan based vc for a long time, did ur implement reached the paper's performance? Both MOS or MCD score?

And did u tried other audio feature to advance this work?  We always can't totally reach the best result, that puzzled me a lot.

That would be nice if sharing any more details about how to get better result via end-to-end VC

All the best,
Luke Huang

**Comment by dipjyoti92** [comment]
Hi @Lukelluke !
I haven't checked the MCD or MOS but it does not reach the performance from the paper. 
I haven't tried different features but I tried different model architectures and some changes in the objective function. I encountered some improvement but not as good as the authors described in the paper. I will commit to those changes soon.

**Comment by Lukelluke** [comment]
Thank u soooo much! @dipjyoti92
