### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by runningtosun** [dipjyoti92/StarGAN-Voice-Conversion-2#3]
looking forward for your reply.

_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "<ipython-input-30-c184c2f0d259>", line 53, in get_spk_world_feats
    log_f0s_mean, log_f0s_std = logf0_statistics(f0s)
  File "/home/ma-user/work/d50017807/starGAN/utils.py", line 115, in logf0_statistics
    log_f0s_concatenated = np.ma.log(np.concatenate(f0s))
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-33-20d194cab0b1> in <module>()
     53         futures.append(executor.submit(partial(get_spk_world_feats, spk_path, mc_dir_train, mc_dir_test, sample_rate)))
     54     print(futures)
---> 55     result_list = [future.result() for future in tqdm(futures)]
     56 #     print(result_list)
     57     sys.exit(0)

<ipython-input-33-20d194cab0b1> in <listcomp>(.0)
     53         futures.append(executor.submit(partial(get_spk_world_feats, spk_path, mc_dir_train, mc_dir_test, sample_rate)))
     54     print(futures)
---> 55     result_list = [future.result() for future in tqdm(futures)]
     56 #     print(result_list)
     57     sys.exit(0)

~/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

~/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: need at least one array to concatenate

**Comment by dipjyoti92** [comment]
What are the dimensions of f0s and coded_sps? The error is probably because your paths are not correct.

**Comment by runningtosun** [comment]
> f0和coded_sps的维数是多少？该错误可能是因为您的路径不正确。

I use my own dataset, and different from vctk, but the folder structure is the same.

**Comment by runningtosun** [comment]
thank you,I'll debug it again
